"""fix constraints

Revision ID: 611b12c44806
Revises: c822ec2e8872
Create Date: 2026-03-02 08:15:01.717641

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "611b12c44806"
down_revision: Union[str, Sequence[str], None] = "c822ec2e8872"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accounts_history",
        "delta",
        existing_type=sa.NUMERIC(),
        type_=sa.Float(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.drop_constraint(op.f("goals_user_id_fkey"), "goals", type_="foreignkey")
    op.create_foreign_key(
        "fk_goal_user",
        "goals",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("fk_goal_user", "goals", type_="foreignkey")
    op.create_foreign_key(
        op.f("goals_user_id_fkey"), "goals", "users", ["user_id"], ["id"]
    )
    op.alter_column(
        "accounts_history",
        "delta",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
